name: "Security Scan"

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run CodeQL
        uses: github/codeql-action/analyze@v2

      - name: Run Secret Scanning (TruffleHog)
        uses: edplato/trufflehog-actions-scan@v2.0.6
        with:
          scanArguments: "--entropy=True --json"

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
